### ISSUE TITLE
[context] - Can't pass relative path

### ISSUE THREAD

**Issue by tbellavia** [Cardiox12/TheExecutor#7]
# Can't pass relative path

The context file must contain only relative path as we can't pass relative path for Docker volume.
We must indicate this specification in README.md

# Example

For example, resources must contain absolute paths in context file.

```yaml
snippets:
    path: /tmp/.out/snippets
resources:
    path: /tmp/.out/resources
```
